import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '../(platform)/_components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="space-y-36">
      <Navbar />
      <div>{children}</div>
    </div>
  );
}
