import type { Metadata } from 'next';
import '../globals.css';
import { auth } from '@clerk/nextjs/server';
import { OrganizationList } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PlatformLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get the organization ID from the session
  const { orgId } = auth();

  // If the user has an active organization, render the children
  if (orgId) {
    return <section>{children}</section>;
  }

  // If the user does not have an active organization, render the organization selection page
  return (
    <section className="grid min-h-screen place-items-center">
      <OrganizationList hidePersonal={true} />
    </section>
  );
}
