import '../globals.css';
import type { Metadata } from 'next';
import { auth } from '@clerk/nextjs/server';
import { OrganizationList } from '@clerk/nextjs';
import Navbar from './_components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PlatformLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get the organization ID from the session
  const { orgId } = auth();

  // If the user has an active organization, render the children
  if (orgId) {
    return (
      <section>
        <Navbar />
        <div className="w-3/4 mx-auto">{children}</div>
      </section>
    );
  }

  // If the user does not have an active organization, render the organization selection page
  return (
    <section className="grid min-h-screen place-items-center">
      <OrganizationList hidePersonal={true} />
    </section>
  );
}
